@startuml
[*] --> タイトル画面 : 起動
タイトル画面 : 遊び方
タイトル画面 : メインゲーム
タイトル画面 : オプション
タイトル画面 --> 遊び方詳細画面 : 遊び方をタップ
遊び方詳細画面 : 次へ
遊び方詳細画面 : 戻る
遊び方詳細画面 : タイトルへ戻る
遊び方詳細画面 --> 遊び方詳細画面 : 次へ/戻るをタップ
遊び方詳細画面 --> タイトル画面 : タイトルへ戻るをタップ
タイトル画面 --> ステージ選択画面 : メインゲームをタップ
ステージ選択画面 : タイトルへ戻る
ステージ選択画面 --> タイトル画面 : タイトルへ戻るをタップ
state ステージ選択画面{
    [*] --> ステージ一覧を表示
    ステージ一覧を表示 --> 選択確認 : ステージ選択
    選択確認 : ゲームスタート
    選択確認 : キャンセル
    選択確認 --> ステージ一覧を表示 : キャンセルをタップ
}
選択確認 --> インゲーム内 : ゲームスタートをタップ
state インゲーム内{
    [*] --> ゲームプレイ画面
    ゲームプレイ画面 --> ゲームオーバー画面 : 体力が0になったら
    ゲームプレイ画面 --> クリア画面 : ゴールしたら
    state ゲームオーバー画面{
    ホーム : コンテニュー
    ホーム : タイトルへ戻る
    [*] --> ホーム
    ホーム --> コンテニュー確認 : コンテニューをタップ
    ホーム --> タイトルバック確認 : タイトルへ戻るをタップ
    コンテニュー確認 : はい
    コンテニュー確認 : キャンセル
    タイトルバック確認 : はい
    タイトルバック確認 : キャンセル
    コンテニュー確認 --> ゲームプレイ画面 : はいをタップ
    コンテニュー確認 --> ホーム : はいをタップ
    タイトルバック確認 --> タイトル画面 : タイトルへ戻るをタップ
    タイトルバック確認 --> ホーム : キャンセルをタップ

}
}
タイトル画面 --> オプション画面 : オプションをタップ

@enduml
